<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nitya" ignored="0" name="Login Test" tests="7" failures="1" timestamp="31 Mar 2023 05:01:18 GMT" time="19.243" errors="0">
  <testcase name="openCartLoginTest" time="0.091" classname="com.qa.opencart.tests.LoginTest"/>
  <testcase name="openCartLoginPageUrlTest" time="0.03" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.028" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.018" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.019" classname="com.qa.opencart.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login1] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login1] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
	at com.qa.opencart.tests.LoginTest.openCartLoginPageUrlTest(LoginTest.java:33)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="isForgotPasswordLinkExists" time="1.129" classname="com.qa.opencart.tests.LoginTest"/>
  <testcase name="doLogin" time="3.998" classname="com.qa.opencart.tests.LoginTest"/>
</testsuite> <!-- Login Test -->
