<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Nitya" name="com.qa.opencart.tests.LoginTest" tests="7" failures="1" timestamp="04 Apr 2023 16:35:57 GMT" time="2.111" errors="0">
  <testcase name="openCartLoginTest" time="0.045" classname="com.qa.opencart.tests.LoginTest"/>
  <testcase name="openCartLoginPageUrlTest" time="0.030" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.047" classname="com.qa.opencart.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login1] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login1] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.qa.opencart.tests.LoginTest.openCartLoginPageUrlTest(LoginTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.036" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="openCartLoginPageUrlTest" time="0.026" classname="com.qa.opencart.tests.LoginTest">
    <skipped/>
  </testcase> <!-- openCartLoginPageUrlTest -->
  <testcase name="isForgotPasswordLinkExists" time="0.094" classname="com.qa.opencart.tests.LoginTest"/>
  <testcase name="doLogin" time="1.833" classname="com.qa.opencart.tests.LoginTest"/>
</testsuite> <!-- com.qa.opencart.tests.LoginTest -->
